// models/ChatSession.js
const { DataTypes } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const ChatSession = sequelize.define('ChatSession', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        userId: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'users', // Ensure this matches your actual User table name
                key: 'id',
            },
            onDelete: 'CASCADE',
        },
        title: {
            type: DataTypes.STRING(255),
            allowNull: false, // Or true if a title isn't always required immediately
        },
        clientSessionId: { // ID generated by the client to track the session before DB ID
            type: DataTypes.STRING(255),
            allowNull: false,
            unique: true, // Important for finding the correct session
        },
        historyGcsUrl: { // Store the Google Cloud Storage URI for the history JSON file
            type: DataTypes.STRING(1024), // Adjust size as needed for GCS URIs (e.g., gs://bucket-name/path/to/object)
            allowNull: true, // Can be null if history hasn't been saved yet
            field: 'history_gcs_url' // Explicitly map to the snake_case database column
        },
    }, {
        tableName: 'chat_sessions',
        timestamps: true, // Adds createdAt and updatedAt automatically
    });

    ChatSession.associate = (models) => {
        // Define association: A ChatSession belongs to a User
        ChatSession.belongsTo(models.User, { foreignKey: 'userId', as: 'user' });
    };

    return ChatSession;
};